### PR TITLE
feat(ZEUS-4293): events-service-api

### PR DESCRIPTION
**Pull request by stephenhi**
Added new Events Service API YAML spec (kept spearate as internal from others).

### CODE REVIEW

**Review by alex-myndar — APPROVED** [review]

**Comment by BartoszZabuski** [comment]
Screenshot 2024-04-16 at 17 12 32
 PUT shouldnt allow to update createdAt, updatedAt

**Comment by BartoszZabuski** [comment]
same for creation

Screenshot 2024-04-16 at 17 15 41

**Comment by BartoszZabuski** [comment]
POST shouldnt allow to create a deleted Event

**Comment by BartoszZabuski** [comment]
no `id` needed for POST request in the body

**Comment by BartoszZabuski** [comment]
PUT is missing 500 response

**Pull request merged**
